xwayland disable
output HEADLESS-1 resolution 1280x800
seat seat0 fallback true
font monospace 10
default_border pixel 2
for_window [app_id="org.graphiks.dawn4k.demo"] floating enable
floating_modifier Mod1 normal
exec foot
